name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          minikube status

      - name: Check certs
        run: |
          ls -l -a ~/.minikube
          ls -l -a ~/.minikube/certs
          apt-get install -y openssl
          openssl x509 -in ~/.minikube/cert.pem -text -noout | grep -A1 "Subject Alternative Name"
          echo "Checking what is in kube config"
          ls -l -a ~/.kube
          cat ~/.kube/config

      - name: Run tests
        env:
          NODE_EXTRA_CA_CERTS: /home/runner/.minikube/ca.pem
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        run: bun test
